[[main]]
    # Top-level menu entry
    identifier = "Home"
    name = "Home"
    url = "/"
    weight = 4

[[main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

[[main]]
    # Top-level menu entry
    identifier = "writing"
    name = "Blog"
    url = "/posts/"
    weight = 4
